name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Key Setup
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.FASTAPI_PEM_KEY }}
          known_hosts: 'just accept'

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ec2-16-171-23-80.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: SSH to EC2 and Deploy
        run: |
          ssh -t ubuntu@ec2-16-171-23-80.eu-north-1.compute.amazonaws.com << EOF
            cd fastapi-book-project
            git pull
            if [ ! -d "venv" ]; then
                python3 -m venv venv
            fi
            source venv/bin/activate
            pip install -r requirements.txt
            fuser -k 8000/tcp || true
            gunicorn main:app --bind 0.0.0.0:8000 --workers 1 --threads 4 --worker-class uvicorn.workers.UvicornWorker
          EOF